import { v4 as uuidv4 } from 'uuid'; //install @types/uuid if it exists

export const users = [
    {
        id: 1000,
        firstName: 'admin',
        middleName: 'correspondence',
        lastName: "admin",
        email: "admin@admin.com",
        phoneNumber: "0592566124",
        hireDate: "2022-03-04",
        birthDate: "2024-12-09",
        userStatus: "regular",
        // privilegeGroup: "admin",
        role: "admin",
    },
    /*{
        id: 1001,
        firstName: 'Sponge',
        middleName: 'Bob',
        lastName: "SquarePants",
        email: "fareshatem.fh@outlook.com",
        phoneNumber: "5656565656",
        hireDate: "2022-03-05",
        birthDate: "2024-12-09",
        userStatus: "regular",
        // privilegeGroup: "employee",
        role: "employee",
    },*/
     /*{
        id: 1002,
        firstName: 'Gerardo',
        middleName: 'Samuel',
        lastName: "Vazquez",
        email: "gerardo.vazquez@gmail.com",
        phoneNumber: "1212121212",
        hireDate: "2022-03-05",
        birthDate: "2024-12-09",
        userStatus: "regular",
        // privilegeGroup: "employee",
        role: "employee",
    },*/
     /*{
        id: 1003,
        firstName: 'Juan',
        middleName: 'Carlos',
        lastName: "Lopez",
        email: "juan.lopez@gmail.com",
        phoneNumber: "1234567890",
        hireDate: "2022-03-05",
        birthDate: "2024-12-09",
        userStatus: "regular",
        // privilegeGroup: "employee",
        role: "employee",
    },*/
     /*{
        id: 1004,
        firstName: 'Maria',
        middleName: 'Fernanda',
        lastName: "Lopez",
        email: "maria.fernanda@gmail.com",
        phoneNumber: "7878787878",
        hireDate: "2022-03-05",
        birthDate: "2024-12-09",
        userStatus: "regular",
        // privilegeGroup: "employee",
        role: "employee",
    },*/
     /*{
        id: 1005,
        firstName: 'Ximena',
        middleName: '',
        lastName: "Dias",
        email: "ximena.dias@gmail.com",
        phoneNumber: "8989898989",
        hireDate: "2022-03-05",
        birthDate: "2024-12-09",
        userStatus: "regular",
        // privilegeGroup: "employee",
        role: "employee",
    },*/ 
    /*{
        id: 1006,
        firstName: 'Patrick',
        middleName: '',
        lastName: "Star",
        email: "patrick.star@gmail.com",
        phoneNumber: "5959595959",
        hireDate: "2022-03-05",
        birthDate: "2024-12-09",
        userStatus: "regular",
        // privilegeGroup: "employee",
        role: "employee",
    },*/
];